---
title: "Progress"
author: "Jared Parsons"
date: "3/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# Hello World!

# Jared's update
Progress has been made on all 3 subprojects within this progam. I have been able 






# David


# Catherine


# Riley & Carson Project
Progress 3-28-21: Riley Smith and me have consulted with eachother and know what we need to do to the kineticsgui.py. This includes removing the CSV tab in the header, moving the CSV save button to the spectrotometer tab, and possibly change the font color to white from black. This is dependant on whether or not my kineticsgui.py is having the same issue that his kineticsgui.py is. It also may just be the computer resorting to its default font color, not the kineticsgui.py. We are still doing research on how to complete these objectives and determining how to get the kineticsgui.py work through my terminal.
# This is Carson Palmer, I approve this message^^^^


# Sophie 
Progress 3-28-21: Noah and I have consulted with one another and several outside sources such as coding websites called Data to Fish, cran.rstudio, and Home and Learn - Python. We will be modifying our section of code to allow students to select a file and save is as a .csv file. An error message will be written to ensure that a file is not saved to a filename that does not exist, or some other saving issue occurs. So far, various packages have been explored for use in solving some of our problems. I compiled the following code from several sources to help address the error message part of our project:

filename = 'filename'

def savefileas():
  save_text_as = filedialog.asksaveasfile(mode='w', defaultextension='.csv')

  if save_text_as:
    text_to_save = textArea.get('1.0', 'end-1c')
    save_text_as.write(text_to_save)
    save_text_as.close()
  else:
      messagebox.showinfo("Error", "Cancelled")

def savefile()
  global file.rename
  
  if filename:
    text_area_text = textArea.get('1.0', 'end-1c')
    save_text = open(filename, 'w')
    save_text.write(text_area_text)
    save_text.close()
  else:
      messagebox.showinfo("Error", "No file open")

There are still several issues that need to be addressed but this is what we have as a starting place.
Progress 03/28/21: David and I added the equation for the line of best fits for each of the Michaelis Menton curves in the graph. This equation can be used to calculate the slope using the inputed data points from the substrate.csv file. -Catherine Oakley


# David Mitchell
Progress 3/28/21: Catherine and I have managed to add code within the program to allow for the slope of the graphs to be calculated based on the inputted data points using the Michaelis Mention equation. This equation can also be displayed on the graph. The following is the code that we developed.
#V0=(Vmax[Concentration])/(Km+[Concentration])
text(4e-06,6.5e-07,label="V0=(3.404e-07[Concentration])/(1.323e-07+[Concentration])")
text(4e-06,2.5e-07,label="V0=(8.801e-07[Concentration])/(1.902e-06+[Concentration])")

# Catherine Oakley
Progress 03/28/21: David and I added the equation for the line of best fits for each of the Michaelis Menton curves in the graph. This equation can be used to calculate the slope using the inputed data points from the substrate.csv file. Catherine Oakley
